language: node_js
node_js:
<<<<<<< HEAD
  - "0.10"
=======
    - "0.10"
    - "0.12"
    - "4.2"
    - "iojs-v2.5.0"
>>>>>>> 1322e14ab87fbfcc9cfa9b56cb59a8a5ce399ad7
before_install:
  - npm install npm -g
